// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufsytxrlkuemfbhslcqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmc3l0eHJsa3VlbWZiaHNsY3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NTE5MTEsImV4cCI6MjA1MDUyNzkxMX0.tdXnK5F0_eihchIqFPgdP3sMAWVZYEMzjpVHu9Cwq2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);