services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Semester3  
      MYSQL_DATABASE: mydb 
      MYSQL_USER: user  
      MYSQL_PASSWORD: password  
    ports:
      - "3307:3306" 
    volumes:
      - ./data:/var/lib/mysql  
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
